spring:
  datasource:
    url: jdbc:mysql://localhost:3306/your_db_name?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: your_username
    password: your_password